### ISSUE TITLE
Why are you using a unnecessary table to disable vehicle weapons? 

### ISSUE THREAD

**Issue by PERPGamer** [Swqppingg/AntiFailRP#1]
I have personally made my own script in the past to disable vehicle weapons and other stuff so I'm confused why you are doing a table on the weapons. Instead, you could do something like this: 
`if DoesVehicleHaveWeapons(veh) == 1 then
		vehicleweapon, vehicleweaponhash = GetCurrentPedVehicleWeapon(playerped)
		if vehicleweapon == 1 then
		DisableVehicleWeapon(true, vehicleweaponhash, veh, playerped)
		SetCurrentPedWeapon(playerped, GetHashKey("weapon_unarmed"))
	end
end` 
(From [FLGRPVehiclesOnly](https://github.com/PERPGamer/FLGRPVehiclesOnly/blob/master/client.lua))

**Comment by Swqppingg** [comment]
Fixed, https://github.com/Swqppingg/AntiFailRP/commit/5771eb5d63c0803d0cc13d9a3924e4c2c3a0639f
